---

volumes:
  mariadb: {}

services:

  ##
  ## - nextcloud
  ##
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    pull_policy: always
    env_file:
      - .env
    volumes:
      - ./nextcloud:/config
      - ./data:/data
    expose:
      - 443
    ports:
      - 80:8088
    restart: unless-stopped
    depends_on:
      - mariadb
      - redis

  ##
  ## - mariadb
  ##
  mariadb:
    image: mariadb:latest
    pull_policy: always
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_USER=admin
      - MARIADB_PASSWORD=admin
      - MARIADB_DATABASE=nextcloud
    volumes:
      - mariadb:/var/lib/mysql
      - ./mariadb:/data
    expose:
      - 3306
    restart: unless-stopped

  ##
  ## - redis
  ##
  redis:
    image: redis:latest
    pull_policy: always
    expose:
      - 6379
    restart: unless-stopped
    entrypoint: ["redis-server", "--maxmemory 4096mb", "--maxmemory-policy allkeys-lru", "--appendonly yes"]
